### ISSUE TITLE
endure_call_serve_fn: got initial serve error from the Vertex rpc.Plugin, stopping execution, error: rpc_plugin_serve: address -1919: invalid port

### ISSUE THREAD

**Issue by thyseus** [laravel/octane#276]
- Octane Version: 1.0.0
- Laravel Version: 8.0.41
- PHP Version: 8
- Server & Version: RoadRunner 2.0.6

```
laravel.test_1       |    INFO  Server running…
laravel.test_1       | 
laravel.test_1       |   Local: http://0.0.0.0:80 
laravel.test_1       | 
laravel.test_1       |   Press Ctrl+C to stop the server
laravel.test_1       | 
laravel.test_1       | 2021-05-17 11:16:10,845 INFO success: php entered RUNNING state, process has stayed up for > than 1 seconds (startsecs)
laravel.test_1       | 
laravel.test_1       |    ERROR  handle_serve_command: Serve error:
laravel.test_1       | 
laravel.test_1       |    ERROR         endure_start:
laravel.test_1       | 
laravel.test_1       |    ERROR         endure_serve_internal: Function call error:
laravel.test_1       | 
laravel.test_1       |    ERROR         endure_call_serve_fn: got initial serve error from the Vertex rpc.Plugin, stopping execution, error: rpc_plugin_serve: address -1919: invalid port
laravel.test_1       | 2021-05-17 11:16:10,888 INFO exited: php (exit status 1; not expected)
laravel.test_1       | 2021-05-17 11:16:11,892 INFO spawned: 'php' with pid 54
```

I get this error after installing octane 1.0.0. Any Ideas what this means or what I did wrong ? Where does the port `-1919` come from ? I tried to bind port 80 to port 80 in `docker-compose.yml`:
```
laravel.test:
        build:
            context: ./docker/8.0
            dockerfile: Dockerfile
            args:
                WWWGROUP: '${WWWGROUP}'
        image: sail-8.0/app
        ports:
            - '${APP_PORT:-80}:80'
        environment:
            WWWUSER: '${WWWUSER}'
            LARAVEL_SAIL: 1
        volumes:
            - '.:/var/www/html'
        networks:
            - sail
        depends_on:
            - mysql
            - redis
            - selenium
```

Thanks a lot !
