### ISSUE TITLE
X-Sendfile support for Roadrunner server

### ISSUE THREAD

**Issue by wlhrtr** [laravel/octane#699]
I am currently working on a project where I have to protect quite big files behind an auth middleware.
Because of that, I have to stream the files to the client. The problem is, streaming those files via PHP needs quite a lot of memory / CPU power.

I looked online for solutions and stumbled across `X-Sendfile` header in Roadrunner docs.
https://roadrunner.dev/docs/http-sendfile/2023.x/en

I added the middleware in `.rr.yaml`
``` yaml
http:
    address: '0.0.0.0:8080'
    middleware:
        - gzip
        - static
        - sendfile
```
and updated my controller to send the header
``` php
return response(null, 200, [
    'x-sendfile' => Storage::path($file)
]);
```
but it doesn't work. I just get an empty response.

After that I used a roadrunner specific package to serve my app (`spiral/roadrunner-laravel`) and it works like a charm.

Now I am wondering if this functionality could be integrated into Octane.
