### ISSUE TITLE
running artisan octane:status is slow and consumes much memory

### ISSUE THREAD

**Issue by Cluster2a** [laravel/octane#708]
### Octane Version

2.0.1

### Laravel Version

10.13.5

### PHP Version

8.2

### What server type are you using?

Swoole

### Server Version

5.0.3

### Database Driver & Version

8.0.33

### Description

I am running laravel + octane via swoole in a kubernetes cluster.
When running `artisan octane:status` somehow the result is returned almost a second later - it feels really slow.

Everything resides within the same container, and nothing else is mounted into a possible slow storage.

I added kubernetes health probes for the deployment.yaml:
```yaml
livenessProbe:
  exec:
    command:
      - php
      - artisan
      - 'octane:status'
  periodSeconds: 10
  timeoutSeconds: 3
  failureThreshold: 3
readinessProbe:
  exec:
    command:
      - php
      - artisan
      - 'octane:status'
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
```

Those health probes lead to much more memory consumption in the pod and slow response times of the requests (>2s vs. 40ms).

When running the command, the memory usage seems to be quite big:
![image](https://github.com/laravel/octane/assets/84905165/846edf73-4614-4417-a7cd-2547834aed02)

### Steps To Reproduce

- run `seq 50 | xargs -I -- php artisan octane:status`
- watch the processes within the container
- `php artisan octane:status` consumes much memory

### Workaround
```yaml
livenessProbe:
  exec:
    command:
      - /bin/sh
      - '-c'
      - >-
        kill -0 `cat /app/storage/logs/octane-server-state.json | jq -r
        '.masterProcessId'`
  periodSeconds: 10
  timeoutSeconds: 1
  failureThreshold: 3
readinessProbe:
  exec:
    command:
      - /bin/sh
      - '-c'
      - >-
        kill -0 `cat /app/storage/logs/octane-server-state.json | jq -r
        '.masterProcessId'`
  periodSeconds: 5
  timeoutSeconds: 5
  failureThreshold: 3
```
